version = "1.0"

[main]
name.en = "Lychee configuration"
name.fr = "Configuration de Lychee"

    [main.matomo]
    ask.en = "Matomo url."
    ask.fr = "L'url de matomo."
    type = "url"
    optional = true
