#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=1G

timezone="$(cat /etc/timezone)"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env public/uploads/"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating configuration..."

# ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# INSTALL APP WITH COMPOSER
#=================================================
ynh_script_progression "Installing app with Composer..."

ynh_composer_install
ynh_composer_exec install --no-dev
ynh_nodejs_install

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Configuring $app..."

ynh_composer_exec dump-autoload

pushd "$install_dir"

         ynh_hide_warnings npm install
         ynh_hide_warnings npm run build
	"php$php_version" artisan key:generate -n --force --env

	"php$php_version" artisan migrate -n --force
	"php$php_version" artisan config:clear -n
	"php$php_version" artisan config:cache -n
	"php$php_version" artisan view:clear
popd

chmod -R 775 /home/yunohost.app/$app/
chgrp "$app" -R "$install_dir/storage" "$install_dir/public/dist" "$install_dir/public/sym" "$data_dir/uploads"
chmod -R 2775 "$install_dir/storage" "$install_dir/app" "$install_dir/public/dist" "$install_dir/public/sym" "$data_dir/uploads" "$install_dir/bootstrap/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
