#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

timezone="$(cat /etc/timezone)"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=4

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --keep=".env" #--full_replace=1 

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating a configuration file..." --weight=1

ynh_add_config --template=".env.example" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# INSTALL APP WITH COMPOSER
#=================================================
ynh_script_progression --message="Installing app with Composer..." --weight=1

ynh_install_composer

#=================================================
# BUILDING
#=================================================
ynh_script_progression --message="Configuring $app..." --weight=4

ynh_exec_warn_less ynh_composer_exec --commands="dump-autoload"

pushd "$install_dir"
	"php$phpversion" artisan key:generate -n --force --env
	"php$phpversion" artisan migrate -n --force
	"php$phpversion" artisan config:clear -n
	"php$phpversion" artisan config:cache -n
	"php$phpversion" artisan view:clear
popd

chmod 750 "$install_dir"
chmod 750 "$install_dir/bootstrap/cache"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
